### ISSUE TITLE
unable to build vdr 2.3.1 with epgsearch

### ISSUE THREAD

**Issue by dersch81** [flensrocker/vdr-plugin-epgsearch#2]
Hi, i get this error:

*** Plugin epgsearch:
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c  -DSENDMAIL='"/usr/sbin/sendmail"' -DPLUGIN_NAME_I18N='"epgsearch"' -I/home/dirk/proc/vdr/include  -o blacklist.o blacklist.c
blacklist.c: In constructor ‘cBlacklist::cBlacklist()’:
blacklist.c:50:18: error: ‘Channels’ was not declared in this scope
     channelMin = Channels.GetByNumber(cDevice::CurrentChannel());
                  ^
blacklist.c: In member function ‘bool cBlacklist::Parse(const char*)’:
blacklist.c:334:17: error: ‘Channels’ was not declared in this scope
    channelMin = Channels.GetByChannelID(tChannelID::FromString(channelMinbuffer), true, true);
                 ^
blacklist.c: In member function ‘cEvent* cBlacklist::GetEventByBlacklist(const cSchedule*, const cEvent*, int)’:
blacklist.c:521:43: error: invalid conversion from ‘const cEvent*’ to ‘cEvent*’ [-fpermissive]
       p1 = schedules->Events()->Next(Start);
                                           ^
blacklist.c:523:39: error: invalid conversion from ‘const cEvent*’ to ‘cEvent*’ [-fpermissive]
       p1 = schedules->Events()->First();
                                       ^
blacklist.c:548:58: error: invalid conversion from ‘const cEvent*’ to ‘cEvent*’ [-fpermissive]
   for (cEvent *p = p1; p; p = schedules->Events()->Next(p))
                                                          ^
blacklist.c: In member function ‘cSearchResults* cBlacklist::Run(cSearchResults*, int)’:
blacklist.c:638:17: error: ‘Schedules’ is not a member of ‘cSchedules’
     schedules = cSchedules::Schedules(schedulesLock);
                 ^
blacklist.c:647:22: error: ‘Channels’ was not declared in this scope
  cChannel* channel = Channels.GetByChannelID(Schedule->ChannelID(),true,true);
                      ^
make[1]: *** [blacklist.o] Fehler 1

Any idea why?

**Comment by flensrocker** [comment]
First: this is no official source for epgsearch and vdr 2.3.x. There are several patches floating around at vdr-portal.de, which I haven't integrated into this git.

Additionally I stopped hacking on epgsearch, instead I started epg2timer. That was easier for me.

And last: use the vdr-2.3.1 branch... :)
